version: '3.8'

services:
  app:
    image: php:8.2-cli
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveluser
      MYSQL_USER: user
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
